import {
  AutoIncrement,
  BelongsTo,
  Column,
  DataType,
  Default,
  ForeignKey,
  Model,
  PrimaryKey,
  Table,
  Unique,
} from 'sequelize-typescript';
import type { CreationOptional, InferAttributes, InferCreationAttributes } from 'sequelize';
import { Account } from '@/Data/Models/Account.js';
import type {
  AppearanceData,
  BleedingStatus,
  BloodType,
  CharacterStatus,
  Gender,
  InjuryStatus,
} from '@Shared/Constants/Character.js';

/**
 * One character belonging to an Account.
 *
 *   - `ID` is the global PK; UI never sees it as a slot.
 *   - `(AccountID, SlotID)` is unique - SlotID is the per-account
 *     "Slot 1 / Slot 2 / ..." pointer the UI displays. Slot survives
 *     soft delete so a restored character keeps its label.
 *   - `(FirstName, LastName)` is globally unique across Active +
 *     Deleted rows. Strict-formal RP policy - no second "John Doe"
 *     ever.
 *   - Forensic IDs (Mask / DNA / Fingerprint / SSN) and
 *     BankAccountNumber share the same 10-char Crockford base32
 *     format. Generated by ForensicIDService at creation, never
 *     mutated.
 *   - `AppearanceData` is a typed JSON column (see
 *     Shared/Constants/Character.AppearanceData). Clothing + props
 *     live on a future Wardrobe / Outfit table, not here.
 *   - Position + heading + world default to the legacy ragemp Airport
 *     coord (see AuthSkybox.DefaultSpawn). The DB enforces NOT NULL and
 *     the column DEFAULTs land on a fresh INSERT; SpawnService reads the
 *     persisted value verbatim. SaveRuntime overwrites on `playerDropped`
 *     (and on character switch when that flow ships) - no recurring tick.
 *   - HP / AP / InjuryStatus / BleedingStatus persist verbatim.
 *     A character that died in-game reconnects dead until the
 *     future injury system handles revival.
 *   - Status='Deleted' is a soft delete; the row stays so the name
 *     and forensic IDs remain reserved.
 *
 * Column mappings: every column carries an explicit `field:` so
 * PascalCase TS names map to snake_case DB columns without lodash
 * mangling acronyms (`DnaID` -> `dna_id`, not `dna_i_d`).
 */
@Table({
  tableName: 'characters',
  timestamps: true,
  createdAt: 'CreatedAt',
  updatedAt: 'UpdatedAt',
  underscored: false,
})
export class Character extends Model<
  InferAttributes<Character>,
  InferCreationAttributes<Character>
> {
  @PrimaryKey
  @AutoIncrement
  @Column({ type: DataType.BIGINT.UNSIGNED, field: 'id' })
  declare ID: CreationOptional<string>;

  @ForeignKey(() => Account)
  @Column({ type: DataType.BIGINT.UNSIGNED, field: 'account_id', allowNull: false })
  declare AccountID: string;

  @BelongsTo(() => Account)
  declare Account?: Account;

  @Column({ type: DataType.TINYINT.UNSIGNED, field: 'slot_id', allowNull: false })
  declare SlotID: number;

  @Column({ type: DataType.STRING(32), field: 'first_name', allowNull: false })
  declare FirstName: string;

  @Column({ type: DataType.STRING(32), field: 'last_name', allowNull: false })
  declare LastName: string;

  @Column({ type: DataType.DATEONLY, field: 'birth_date', allowNull: false })
  declare BirthDate: string;

  @Column({
    type: DataType.ENUM('Male', 'Female'),
    field: 'gender',
    allowNull: false,
  })
  declare Gender: Gender;

  @Column({
    type: DataType.ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'),
    field: 'blood_type',
    allowNull: false,
  })
  declare BloodType: BloodType;

  @Default('Active')
  @Column({
    type: DataType.ENUM('Active', 'Deleted'),
    field: 'status',
    allowNull: false,
  })
  declare Status: CreationOptional<CharacterStatus>;

  @Column({ type: DataType.DATE, field: 'deleted_at', allowNull: true })
  declare DeletedAt: CreationOptional<Date | null>;

  // ── Forensic / financial identifiers (10-char Crockford base32) ─────
  @Unique
  @Column({ type: DataType.STRING(10), field: 'mask_id', allowNull: false })
  declare MaskID: string;

  @Unique
  @Column({ type: DataType.STRING(10), field: 'dna_id', allowNull: false })
  declare DnaID: string;

  @Unique
  @Column({ type: DataType.STRING(10), field: 'fingerprint_id', allowNull: false })
  declare FingerprintID: string;

  @Unique
  @Column({ type: DataType.STRING(10), field: 'ssn_id', allowNull: false })
  declare SsnID: string;

  @Unique
  @Column({ type: DataType.STRING(10), field: 'bank_account_number', allowNull: true })
  declare BankAccountNumber: CreationOptional<string | null>;

  // ── Vitals + free-text description ──────────────────────────────────
  @Column({ type: DataType.SMALLINT, field: 'height_cm', allowNull: true })
  declare HeightCm: CreationOptional<number | null>;

  @Column({ type: DataType.SMALLINT, field: 'weight_kg', allowNull: true })
  declare WeightKg: CreationOptional<number | null>;

  @Column({ type: DataType.TEXT, field: 'physical_description', allowNull: true })
  declare PhysicalDescription: CreationOptional<string | null>;

  @Column({ type: DataType.TEXT, field: 'clothing_description', allowNull: true })
  declare ClothingDescription: CreationOptional<string | null>;

  // ── Appearance (typed JSON, NOT NULL - editor returns full payload) ─
  @Column({ type: DataType.JSON, field: 'appearance_data', allowNull: false })
  declare AppearanceData: AppearanceData;

  @Default(false)
  @Column({ type: DataType.BOOLEAN, field: 'is_masked', allowNull: false })
  declare IsMasked: CreationOptional<boolean>;

  // ── Combat / health ────────────────────────────────────────────────
  @Default(100)
  @Column({ type: DataType.TINYINT.UNSIGNED, field: 'hp', allowNull: false })
  declare HP: CreationOptional<number>;

  @Default(0)
  @Column({ type: DataType.TINYINT.UNSIGNED, field: 'ap', allowNull: false })
  declare AP: CreationOptional<number>;

  @Default('Healthy')
  @Column({
    type: DataType.ENUM('Healthy', 'Unconscious', 'BadlyWounded', 'Dead'),
    field: 'injury_status',
    allowNull: false,
  })
  declare InjuryStatus: CreationOptional<InjuryStatus>;

  @Default('NotBleeding')
  @Column({
    type: DataType.ENUM('NotBleeding', 'LightBleeding', 'MediumBleeding', 'HeavyBleeding'),
    field: 'bleeding_status',
    allowNull: false,
  })
  declare BleedingStatus: CreationOptional<BleedingStatus>;

  // ── World position ─────────────────────────────────────────────────
  // Columns carry NOT NULL defaults sourced from Shared/Constants/
  // AuthSkybox.DefaultSpawn so a brand new character has the Airport
  // coords from the moment of INSERT. SaveRuntime overwrites them on
  // disconnect or character switch; subsequent spawns read the saved
  // values verbatim.
  @Default(0)
  @Column({ type: DataType.INTEGER, field: 'world', allowNull: false })
  declare World: CreationOptional<number>;

  @Default('-1038.700')
  @Column({ type: DataType.DECIMAL(10, 3), field: 'position_x', allowNull: false })
  declare PositionX: CreationOptional<string>;

  @Default('-2738.600')
  @Column({ type: DataType.DECIMAL(10, 3), field: 'position_y', allowNull: false })
  declare PositionY: CreationOptional<string>;

  @Default('13.800')
  @Column({ type: DataType.DECIMAL(10, 3), field: 'position_z', allowNull: false })
  declare PositionZ: CreationOptional<string>;

  @Default('0.000')
  @Column({ type: DataType.DECIMAL(10, 3), field: 'heading', allowNull: false })
  declare Heading: CreationOptional<string>;

  // ── Economy ────────────────────────────────────────────────────────
  @Default('0.00')
  @Column({ type: DataType.DECIMAL(12, 2), field: 'cash', allowNull: false })
  declare Cash: CreationOptional<string>;

  @Default('0.00')
  @Column({ type: DataType.DECIMAL(12, 2), field: 'bank', allowNull: false })
  declare Bank: CreationOptional<string>;

  @Default('0.00')
  @Column({ type: DataType.DECIMAL(12, 2), field: 'bank_restricted', allowNull: false })
  declare BankRestricted: CreationOptional<string>;

  // ── Progression ────────────────────────────────────────────────────
  @Default(1)
  @Column({ type: DataType.INTEGER, field: 'level', allowNull: false })
  declare Level: CreationOptional<number>;

  @Default(0)
  @Column({ type: DataType.BIGINT, field: 'experience_points', allowNull: false })
  declare ExperiencePoints: CreationOptional<string>;

  @Default(0)
  @Column({ type: DataType.INTEGER, field: 'daily_xp_earned', allowNull: false })
  declare DailyXPEarned: CreationOptional<number>;

  @Column({ type: DataType.DATE, field: 'daily_xp_reset_at', allowNull: true })
  declare DailyXPResetAt: CreationOptional<Date | null>;

  @Default(0)
  @Column({ type: DataType.INTEGER, field: 'weekly_xp_earned', allowNull: false })
  declare WeeklyXPEarned: CreationOptional<number>;

  @Column({ type: DataType.DATE, field: 'weekly_xp_reset_at', allowNull: true })
  declare WeeklyXPResetAt: CreationOptional<Date | null>;

  @Default(0)
  @Column({ type: DataType.INTEGER, field: 'monthly_xp_earned', allowNull: false })
  declare MonthlyXPEarned: CreationOptional<number>;

  @Column({ type: DataType.DATE, field: 'monthly_xp_reset_at', allowNull: true })
  declare MonthlyXPResetAt: CreationOptional<Date | null>;

  @Default(0)
  @Column({ type: DataType.INTEGER, field: 'playtime_minutes', allowNull: false })
  declare PlaytimeMinutes: CreationOptional<number>;

  // ── Audit ──────────────────────────────────────────────────────────
  @Column({ type: DataType.STRING(45), field: 'creation_ip', allowNull: true })
  declare CreationIP: CreationOptional<string | null>;

  @Column({ type: DataType.DATE, field: 'last_login_at', allowNull: true })
  declare LastLoginAt: CreationOptional<Date | null>;

  @Column({ type: DataType.DATE, field: 'created_at', allowNull: false })
  declare CreatedAt: CreationOptional<Date>;

  @Column({ type: DataType.DATE, field: 'updated_at', allowNull: false })
  declare UpdatedAt: CreationOptional<Date>;
}
